name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write  # peaceiris 需要写权限

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .  # 部署根目录（即当前 index.html 所在位置）
          publish_branch: gh-pages
